---
- name: Install Nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Copy nginx config
  copy:
    src: conf.d/
    dest: /etc/nginx/conf.d
    mode: preserve

- name: Copy ssl config
  copy:
    src: ssl/
    dest: /etc/ssl
    mode: preserve

- name: Restart Nginx
  service:
    name: nginx
    state: restarted